### ISSUE TITLE
Showing Error

### ISSUE THREAD

**Issue by imalisiddique** [AlxMedia/enspire#1]
Warning: Illegal string offset 'background-color' in /home/alisicas/public_html/freething.xyz/wp-content/themes/enspire/functions/dynamic-styles.php on line 204

Warning: Illegal string offset 'background-image' in /home/alisicas/public_html/freething.xyz/wp-content/themes/enspire/functions/dynamic-styles.php on line 205

Warning: Illegal string offset 'background-position' in /home/alisicas/public_html/freething.xyz/wp-content/themes/enspire/functions/dynamic-styles.php on line 206

Warning: Illegal string offset 'background-attachment' in /home/alisicas/public_html/freething.xyz/wp-content/themes/enspire/functions/dynamic-styles.php on line 207

Warning: Illegal string offset 'background-repeat' in /home/alisicas/public_html/freething.xyz/wp-content/themes/enspire/functions/dynamic-styles.php on line 208

Warning: Illegal string offset 'background-size' in /home/alisicas/public_html/freething.xyz/wp-content/themes/enspire/functions/dynamic-styles.php on line 209

**Comment by AlxMedia** [comment]
Thanks for reporting. Try pressing save once in the theme options panel and see if it goes away.
